const terminalMessages = [
  "[INFO] Booting OS...",
  "[SYSTEM] Initializing hardware...",
  "[INFO] Loading system configuration...",
  "[INFO] Checking network connection...",
  "[NETWORK] Network connected successfully!",
  "[DRIVERS] Loading drivers...",
  "[INFO] Starting services...",
  "[SECURITY] Verifying system integrity...",
  "[UI] Initializing user interface components...",
  "[UI] Applying theme settings...",
  "[UI] Loading desktop background...",
  "[UI] Configuring taskbar and start menu...",
  "[APPLICATIONS] Loading default applications...",
  "[APPLICATIONS] Setting up file explorer...",
  "[APPLICATIONS] Configuring text editor...",
  "[APPLICATIONS] Initializing start menu items...",
  "[APPLICATIONS] Preparing notification system...",
  "[PORTFOLIO] Loading portfolio assets...",
  "[PORTFOLIO] Fetching project data...",
  "[PORTFOLIO] Setting up project sections...",
  "[PORTFOLIO] Initializing project overview...",
  "[PORTFOLIO] Loading technology stack...",
  "[PORTFOLIO] Configuring project structure...",
  "[PORTFOLIO] Applying component styles...",
  "[PORTFOLIO] Setting up state management...",
  "[PORTFOLIO] Loading animations and transitions...",
  "[PORTFOLIO] Ensuring responsive design...",
  "[PORTFOLIO] Checking accessibility features...",
  "[PORTFOLIO] Optimizing performance...",
  "[PORTFOLIO] Preparing documentation sections...",
  "[PORTFOLIO] Verifying all components...",
  "[PORTFOLIO] Finalizing portfolio setup...",
  "[INFO] Portfolio OS fully loaded. Explore your projects!",
];

export { terminalMessages };
