import { FilesState } from "@/redux/slices/fileSlice";

const portfolioFileSystem: FilesState = {
  fileSystem: {
    'root': {
      id: 'root',
      name: 'Root',
      icon: "/icons/explorer/folder-solid.svg",
      type: 'folder',
      children: ['About', 'Projects', 'Skills', 'Education', 'Experience', 'Contact'],
      createdAt: new Date().toISOString(),
      modifiedAt: new Date().toISOString(),
      parentId: null,
    },
    'About': {
      id: 'About',
      name: 'About',
      type: 'folder',
      icon: "/icons/explorer/folder-solid.svg",
      children: ['Profile.md', 'Resume.pdf'],
      createdAt: new Date().toISOString(),
      modifiedAt: new Date().toISOString(),
      parentId: 'root',
    },
    'Projects': {
      id: 'Projects',
      name: 'Projects',
      type: 'folder',
      icon: "/icons/explorer/folder-solid.svg",
      children: ['WebApp1', 'WebApp2', 'MobileApp'],
      createdAt: new Date().toISOString(),
      modifiedAt: new Date().toISOString(),
      parentId: 'root',
    },
    'Skills': {
      id: 'Skills',
      name: 'Skills',
      type: 'folder',
      icon: "/icons/explorer/folder-solid.svg",
      children: ['TechnicalSkills.md', 'SoftSkills.md'],
      createdAt: new Date().toISOString(),
      modifiedAt: new Date().toISOString(),
      parentId: 'root',
    },
    'Education': {
      id: 'Education',
      name: 'Education',
      type: 'folder',
      icon: "/icons/explorer/folder-solid.svg",
      children: ['Degree.md', 'Certifications.md'],
      createdAt: new Date().toISOString(),
      modifiedAt: new Date().toISOString(),
      parentId: 'root',
    },
    'Experience': {
      id: 'Experience',
      name: 'Experience',
      type: 'folder',
      icon: "/icons/explorer/folder-solid.svg",
      children: ['Job1.md', 'Job2.md', 'Freelance.md'],
      createdAt: new Date().toISOString(),
      modifiedAt: new Date().toISOString(),
      parentId: 'root',
    },
    'Contact': {
      id: 'Contact',
      name: 'Contact',
      type: 'folder',
      icon: "/icons/explorer/folder-solid.svg",
      children: ['ContactInfo.md', 'SocialMedia.md'],
      createdAt: new Date().toISOString(),
      modifiedAt: new Date().toISOString(),
      parentId: 'root',
    },
    'WebApp1': {
      id: 'WebApp1',
      name: 'WebApp1',
      type: 'folder',
      icon: "/icons/explorer/folder-solid.svg",
      children: ['Description.md', 'Screenshot.png', 'TechStack.md'],
      createdAt: new Date().toISOString(),
      modifiedAt: new Date().toISOString(),
      parentId: 'Projects',
    },
    'WebApp2': {
      id: 'WebApp2',
      name: 'WebApp2',
      type: 'folder',
      icon: "/icons/explorer/folder-solid.svg",
      children: ['Description.md', 'Screenshot.png', 'TechStack.md'],
      createdAt: new Date().toISOString(),
      modifiedAt: new Date().toISOString(),
      parentId: 'Projects',
    },
    'MobileApp': {
      id: 'MobileApp',
      name: 'MobileApp',
      type: 'folder',
      icon: "/icons/explorer/folder-solid.svg",
      children: ['Description.md', 'Screenshot.png', 'TechStack.md'],
      createdAt: new Date().toISOString(),
      modifiedAt: new Date().toISOString(),
      parentId: 'Projects',
    },
    'Profile.md': {
      id: 'Profile.md',
      name: 'Profile.md',
      type: 'file',
      icon: "/icons/explorer/file-solid.svg",
      content: "# About Me\n\nI'm a passionate frontend developer with expertise in creating responsive and user-friendly web applications.",
      size: 120,
      extension: 'md',
      createdAt: new Date().toISOString(),
      modifiedAt: new Date().toISOString(),
      parentId: 'About',
    },
    'Resume.pdf': {
      id: 'Resume.pdf',
      name: 'Resume.pdf',
      type: 'file',
      icon: "/icons/explorer/file-pdf-solid.svg",
      content: "My professional resume in PDF format",
      size: 1024 * 1024 * 2, // 2 MB
      extension: 'pdf',
      createdAt: new Date().toISOString(),
      modifiedAt: new Date().toISOString(),
      parentId: 'About',
    },
    'TechnicalSkills.md': {
      id: 'TechnicalSkills.md',
      name: 'TechnicalSkills.md',
      type: 'file',
      icon: "/icons/explorer/file-solid.svg",
      content: "# Technical Skills\n\n- HTML5, CSS3, JavaScript\n- React, Vue.js\n- Node.js, Express\n- Git, GitHub\n- Responsive Web Design",
      size: 150,
      extension: 'md',
      createdAt: new Date().toISOString(),
      modifiedAt: new Date().toISOString(),
      parentId: 'Skills',
    },
    'SoftSkills.md': {
      id: 'SoftSkills.md',
      name: 'SoftSkills.md',
      type: 'file',
      icon: "/icons/explorer/file-solid.svg",
      content: "# Soft Skills\n\n- Problem-solving\n- Team collaboration\n- Communication\n- Time management\n- Adaptability",
      size: 120,
      extension: 'md',
      createdAt: new Date().toISOString(),
      modifiedAt: new Date().toISOString(),
      parentId: 'Skills',
    },
    'Degree.md': {
      id: 'Degree.md',
      name: 'Degree.md',
      type: 'file',
      icon: "/icons/explorer/file-solid.svg",
      content: "# Education\n\nBachelor of Science in Computer Science\nUniversity Name, Graduation Year",
      size: 90,
      extension: 'md',
      createdAt: new Date().toISOString(),
      modifiedAt: new Date().toISOString(),
      parentId: 'Education',
    },
    'Certifications.md': {
      id: 'Certifications.md',
      name: 'Certifications.md',
      type: 'file',
      icon: "/icons/explorer/file-solid.svg",
      content: "# Certifications\n\n- Frontend Web Development (FreeCodeCamp)\n- React Developer Certification (Udacity)",
      size: 110,
      extension: 'md',
      createdAt: new Date().toISOString(),
      modifiedAt: new Date().toISOString(),
      parentId: 'Education',
    },
    'Job1.md': {
      id: 'Job1.md',
      name: 'Job1.md',
      type: 'file',
      icon: "/icons/explorer/file-solid.svg",
      content: "# Frontend Developer\n\nCompany Name, Start Date - End Date\n\n- Developed responsive web applications\n- Collaborated with UX/UI designers",
      size: 140,
      extension: 'md',
      createdAt: new Date().toISOString(),
      modifiedAt: new Date().toISOString(),
      parentId: 'Experience',
    },
    'Job2.md': {
      id: 'Job2.md',
      name: 'Job2.md',
      type: 'file',
      icon: "/icons/explorer/file-solid.svg",
      content: "# Web Developer Intern\n\nCompany Name, Start Date - End Date\n\n- Assisted in building company website\n- Learned best practices in web development",
      size: 150,
      extension: 'md',
      createdAt: new Date().toISOString(),
      modifiedAt: new Date().toISOString(),
      parentId: 'Experience',
    },
    'Freelance.md': {
      id: 'Freelance.md',
      name: 'Freelance.md',
      type: 'file',
      icon: "/icons/explorer/file-solid.svg",
      content: "# Freelance Projects\n\n- E-commerce website for local business\n- Portfolio website for photographer",
      size: 100,
      extension: 'md',
      createdAt: new Date().toISOString(),
      modifiedAt: new Date().toISOString(),
      parentId: 'Experience',
    },
    'ContactInfo.md': {
      id: 'ContactInfo.md',
      name: 'ContactInfo.md',
      type: 'file',
      icon: "/icons/explorer/file-solid.svg",
      content: "# Contact Information\n\nEmail: your.email@example.com\nPhone: (123) 456-7890\nLocation: City, Country",
      size: 110,
      extension: 'md',
      createdAt: new Date().toISOString(),
      modifiedAt: new Date().toISOString(),
      parentId: 'Contact',
    },
    'SocialMedia.md': {
      id: 'SocialMedia.md',
      name: 'SocialMedia.md',
      type: 'file',
      icon: "/icons/explorer/file-solid.svg",
      content: "# Social Media\n\n- LinkedIn: [Your LinkedIn Profile]\n- GitHub: [Your GitHub Profile]\n- Twitter: [Your Twitter Handle]",
      size: 130,
      extension: 'md',
      createdAt: new Date().toISOString(),
      modifiedAt: new Date().toISOString(),
      parentId: 'Contact',
    },
    'Description.md': {
      id: 'Description.md',
      name: 'Description.md',
      type: 'file',
      icon: "/icons/explorer/file-solid.svg",
      content: "# Project Description\n\nA brief overview of the project, its goals, and key features.",
      size: 80,
      extension: 'md',
      createdAt: new Date().toISOString(),
      modifiedAt: new Date().toISOString(),
      parentId: 'WebApp1',
    },
    'Screenshot.png': {
      id: 'Screenshot.png',
      name: 'Screenshot.png',
      type: 'file',
      icon: "/icons/explorer-image.svg",
      content: "Project screenshot image",
      size: 1024 * 1024 * 1.5, // 1.5 MB
      extension: 'png',
      createdAt: new Date().toISOString(),
      modifiedAt: new Date().toISOString(),
      parentId: 'WebApp1',
    },
    'TechStack.md': {
      id: 'TechStack.md',
      name: 'TechStack.md',
      type: 'file',
      icon: "/icons/explorer/file-solid.svg",
      content: "# Tech Stack\n\n- Frontend: React, Redux, Styled Components\n- Backend: Node.js, Express\n- Database: MongoDB\n- Deployment: AWS",
      size: 130,
      extension: 'md',
      createdAt: new Date().toISOString(),
      modifiedAt: new Date().toISOString(),
      parentId: 'WebApp1',
    },
  },
  currentDirectory: 'root',
};

export { portfolioFileSystem };